### ISSUE TITLE
TypeError: Object user has no method 'schema'

### ISSUE THREAD

**Issue by willhoag** [wprl/baucis#185]
I'm getting an error that I'm having trouble debugging. Works just fine locally, but on heroku I get a TypeError. Here is some mockup code:

```coffeescript
# ../models/User.coffee
UserSchema = new mongoose.Schema
  shots: { type: [{type: ObjectId, ref: 'shot'}], select: false }
module.exports = mongoose.model('user', UserSchema)
```

```coffeescript
# ../models/Shot.coffee
ShotSchema = new mongoose.Schema
  owner: {type: ObjectId, ref: 'user'}
module.exports = mongoose.model('shot', ShotSchema)
```

```coffeescript
# express.coffee
User = require('../models/User')
Shot = require('../models/Shot')
users = baucis.rest('user')
shots = users.vivify('shots').parentPath('owner')
app.use '/api', baucis()
```

And here is the error. I'm having trouble replicating this locally. Any ideas?

```
2014-05-28T07:06:47.607366+00:00 app[web.1]: TypeError: Object user has no method 'schema'
2014-05-28T07:06:47.607374+00:00 app[web.1]:   at Function.controller.vivify (/app/node_modules/baucis/Controller/vivify.js:11:41)
2014-05-28T07:06:47.607376+00:00 app[web.1]:   at module.exports (/app/lib/config/express.coffee:38:17)
2014-05-28T07:06:47.607377+00:00 app[web.1]:   at Object.<anonymous> (/app/server.coffee:16:1)
2014-05-28T07:06:47.607379+00:00 app[web.1]:   at Object.<anonymous> (/app/server.coffee:2:1)
2014-05-28T07:06:47.607380+00:00 app[web.1]:   at Module._compile (module.js:456:26)
```

**Comment by wprl** [comment]
This should be fixed in 1.0.0.  I'll be keeping an eye out for ongoing dependency issues but I believe I have solved the problem.
