### ISSUE TITLE
server crash when some specific error happened

### ISSUE THREAD

**Issue by zzswang** [wprl/baucis#212]
{ [TypeError: Cannot use 'in' operator to search for '_id' in {name:"aaa", value
:"bbb", category:"ccc"}] domainThrown: true }
TypeError: Cannot call method 'toString' of undefined
    at ServerResponse.writeHead (http.js:1180:45)
    at ServerResponse.writeHead (D:\Workspace\juli\node_modules\express-session\
node_modules\on-headers\index.js:43:19)
    at ServerResponse._implicitHeader (http.js:1131:8)
    at ServerResponse.OutgoingMessage.end (http.js:920:10)
    at D:\Workspace\juli\node_modules\express-session\index.js:185:15
    at Object._onImmediate (D:\Workspace\juli\node_modules\express-session\sessi
on\memory.js:81:11)
    at processImmediate [as _immediateCallback] (timers.js:330:15)

http.js:1180
  var statusLine = 'HTTP/1.1 ' + statusCode.toString() + ' ' +
                                            ^
TypeError: Cannot call method 'toString' of undefined
    at ServerResponse.writeHead (http.js:1180:45)
    at ServerResponse.writeHead (D:\Workspace\juli\node_modules\express-session\
node_modules\on-headers\index.js:43:19)
    at ServerResponse._implicitHeader (http.js:1131:8)
    at ServerResponse.OutgoingMessage.end (http.js:920:10)
    at D:\Workspace\juli\node_modules\express-session\index.js:185:15
    at Object._onImmediate (D:\Workspace\juli\node_modules\express-session\sessi
on\memory.js:81:11)
    at processImmediate [as _immediateCallback] (timers.js:330:15)

**Comment by wprl** [comment]
Thanks for reporting this.  From the stack trace this doesn't look like an issue with baucis.  If you could post some code to reproduce the error, we can reopen this and take a more detailed look.
