### ISSUE TITLE
issue with sub-document population

### ISSUE THREAD

**Issue by 4fthawaiian** [wprl/baucis#294]
given the following:
```
var full_game_controller = baucis.rest('Game');
full_game_controller.fragment('/fullgame');
full_game_controller.query(function (request, response, next) {
    request.baucis.query.populate([
        {
            path: 'levels',
            options: {
                populate: [
                    'boards.board',
                    'wireframe'
                ]
            }
        }
...
```

Neither of the sub-documents "board.board" or "wireframe" populate successfully. However, in the following:

```
var full_game_controller = baucis.rest('Game');
full_game_controller.fragment('/fullgame');
full_game_controller.query(function (request, response, next) {
    request.baucis.query.populate([
        {
            path: 'levels',
            options: {
                populate: [
                    'boards.board',
                ]
            }
        }
...
```

"boards.board" populates just fine. I've also tried using the "path" syntax as such:

```
...
            options: {
                populate: [
                    {path: 'boards.board' },
                    {path: "wireframe"}
                ]
...
```

But, while this works with only the single item "boards.board" it fails with another item in the array:

```
/Users/bradleymccrorey/canvas_socket/node_modules/mongoose/node_modules/mongodb/lib/utils.js:97
    process.nextTick(function() { throw err; });
                                        ^
TypeError: utils.populate: invalid path. Expected string. Got typeof `object`
    at populate (/Users/bradleymccrorey/canvas_socket/node_modules/mongoose/lib/utils.js:561:11)
    at Query.populate (/Users/bradleymccrorey/canvas_socket/node_modules/mongoose/lib/query.js:2452:28)
    at Query.setOptions (/Users/bradleymccrorey/canvas_socket/node_modules/mongoose/node_modules/mquery/lib/mquery.js:185:20)
    at Query.setOptions (/Users/bradleymccrorey/canvas_socket/node_modules/mongoose/lib/query.js:882:32)
    at Query (/Users/bradleymccrorey/canvas_socket/node_modules/mongoose/node_modules/mquery/lib/mquery.js:56:10)
    at new Query (/Users/bradleymccrorey/canvas_socket/node_modules/mongoose/lib/query.js:67:10)
    at Function.find (/Users/bradleymccrorey/canvas_socket/node_modules/mongoose/lib/model.js:1035:12)
    at populate (/Users/bradleymccrorey/canvas_socket/node_modules/mongoose/lib/model.js:2340:15)
    at Function.Model.populate (/Users/bradleymccrorey/canvas_socket/node_modules/mongoose/lib/model.js:2177:5)
    at QueryStream._onNextObject (/Users/bradleymccrorey/canvas_socket/node_modules/mongoose/lib/querystream.js:232:20)
    at cursorcb (/Users/bradleymccrorey/canvas_socket/node_modules/mongoose/lib/querystream.js:176:10)
    at handleCallback (/Users/bradleymccrorey/canvas_socket/node_modules/mongoose/node_modules/mongodb/lib/utils.js:95:12)
    at /Users/bradleymccrorey/canvas_socket/node_modules/mongoose/node_modules/mongodb/lib/cursor.js:597:5
    at handleCallback (/Users/bradleymccrorey/canvas_socket/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:244:5)
    at nextFunction (/Users/bradleymccrorey/canvas_socket/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:739:5)
    at /Users/bradleymccrorey/canvas_socket/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:664:7
```

Please let me know the expected behavior, and whether I can supply any further information.

**Comment by 4fthawaiian** [comment]
```
        {
            path: 'levels',
            options: {
                populate: 'boards.board+wireframe+animations.animation'
            }
        },
```
also fails :/

**Comment by 4fthawaiian** [comment]
wait, this worked. Heh. nothing to see here.
```
        {
            path: 'levels',
            options: {
                populate: 'boards.board wireframe animations.animation'
            }
        },
```
