### ISSUE TITLE
TypeError: controller.model(...).plural is not a function

### ISSUE THREAD

**Issue by capaj** [wprl/baucis#302]
Using mongoose 4.2.8 and baucis 1.6.3 I get this error:
```
TypeError: controller.model(...).plural is not a function
    at Function.<anonymous> (/home/capaj/git_projects/Moonridge/node_modules/baucis/Controller/configure.js:35:64)
    at getter (/home/capaj/git_projects/Moonridge/node_modules/deco/index.js:66:37)
    at Function.o.(anonymous function) [as fragment] (/home/capaj/git_projects/Moonridge/node_modules/deco/index.js:85:20)
    at /home/capaj/git_projects/Moonridge/node_modules/baucis/Api/controllers.js:33:38
    at Array.filter (native)
    at Object.protect.controllers (/home/capaj/git_projects/Moonridge/node_modules/baucis/Api/controllers.js:32:22)
    at /home/capaj/git_projects/Moonridge/node_modules/baucis/Api/controllers.js:39:31
    at Layer.handle [as handle_request] (/home/capaj/git_projects/Moonridge/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/capaj/git_projects/Moonridge/node_modules/express/lib/router/index.js:312:13)
    at /home/capaj/git_projects/Moonridge/node_modules/express/lib/router/index.js:280:7
    at param (/home/capaj/git_projects/Moonridge/node_modules/express/lib/router/index.js:349:14)
    at param (/home/capaj/git_projects/Moonridge/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/home/capaj/git_projects/Moonridge/node_modules/express/lib/router/index.js:410:3)
    at next (/home/capaj/git_projects/Moonridge/node_modules/express/lib/router/index.js:271:10)
    at /home/capaj/git_projects/Moonridge/node_modules/baucis/Api/index.js:37:5
    at Layer.handle [as handle_request] (/home/capaj/git_projects/Moonridge/node_modules/express/lib/router/layer.js:95:5)

```

When I try to do 
```
baucis.Controller.decorators(function (options, protect) {
  var controller = this
	controller.model(function (request, response, next) {
	  console.log('model', request.baucis.model)
	  next()
	})
})
```

Am I doing something wrong, or do you have a bug there?

**Comment by capaj** [comment]
My bad, thanks to https://github.com/hippich/baucis-access/blob/master/index.js I was able to get my model. Closing.

**Comment by wprl** [comment]
Excellent 👍🏼 Do you feel there's any way the documentation or syntax could be improved to make the solution more obvious?
