### ISSUE TITLE
DeprecationWarning: Mongoose: Query.prototype.stream() is deprecated

### ISSUE THREAD

**Issue by tungv** [wprl/baucis#317]
`DeprecationWarning: Mongoose: Query.prototype.stream() is deprecated in mongoose >= 4.5.0, use Query.prototype.cursor() instead`

I'm using `mongoose: ^4.9.3` at the moment

**Comment by tungv** [comment]
The interesting point is that I cannot find any usage of `stream()` in your codebase using github search

**Comment by mozi** [comment]
Look in
> Controller/send.js

**Comment by pjmolina** [comment]
@mozi is right. `Controller/send.js` at lines [128](https://github.com/wprl/baucis/blob/master/Controller/send.js#L128) & [174](https://github.com/wprl/baucis/blob/master/Controller/send.js#L174) uses `stream()`.

**Comment by mozi** [comment]
please note that changing it to .cursor() instead should work, although there is a massive performance drop when populate is used extensively, this is an issue with mongoose 4.5.x, 4.6.x, 4.7.x and 4.8.x

currently sticking with mongoose 4.4.x for prod, while testing with the latest 4.9.x

**Comment by mozi** [comment]
in addition to the performance drop, there is intermittent error thrown when switching to .cursor()
`MongoError: Cursor is closed,
at Function.MongoError.create (node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\error.js:31:11)
at nextObject (node_modules\\mongoose\\node_modules\\mongodb\\lib\\cursor.js:669:112)
at Cursor.next (node_modules\\mongoose\\node_modules\\mongodb\\lib\\cursor.js:269:12)
at _next (node_modules\\mongoose\\lib\\querycursor.js:269:23)
at QueryCursor._read (node_modules\\mongoose\\lib\\querycursor.js:63:3)
at QueryCursor.Readable.read (_stream_readable.js:348:10)
at readableAddChunk (_stream_readable.js:177:18)
at QueryCursor.Readable.push (_stream_readable.js:134:10)
at node_modules\\mongoose\\lib\\querycursor.js:79:11
at node_modules\\mongoose\\lib\\querycursor.js:320:5
at model.Document.init (node_modules\\mongoose\\lib\\document.js:337:5)
at _create (node_modules\\mongoose\\lib\\querycursor.js:316:12)
at node_modules\\mongoose\\lib\\querycursor.js:296:11
at node_modules\\mongoose\\lib\\model.js:3720:16
at next (node_modules\\mongoose\\lib\\model.js:2935:5)
at next (node_modules\\mongoose\\lib\\model.js:3048:7)
at node_modules\\mongoose\\lib\\query.js:2745:18
at process._tickDomainCallback (internal/process/next_tick.js:129:7)
`

**Comment by mozi** [comment]
The populate performance issue has been fixed in mongoose 4.9.3 as per https://github.com/Automattic/mongoose/issues/5103

**Comment by wprl** [comment]
Baucis2 will replace this code and does not rely on Mongoose.  I'm going to close this but would gladly accept a PR for improving this in Baucis v1.x
