### ISSUE TITLE
Bug in v. 1.6.6: .cursor only support .find method (500)

### ISSUE THREAD

**Issue by pjmolina** [wprl/baucis#326]
When doing `GET /api/<resource>/<id>` the following error (500) is returned:

```
{status: 500, name: "Internal Server Error", message: ".cursor only support .find method (500).",
stack:
"TypeError: .cursor only support .find method
    at Query.cursor (\node_modules\mquery\lib\mquery.js:1721:13)
    at \node_modules\baucis\Controller\send.js:174:40
    at Layer.handle [as handle_request] (\node_modules\express\lib\router\layer.js:95:5)
    at next (\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (\node_modules\express\lib\router\layer.js:95:5)
    at \node_modules\express\lib\router\index.js:281:22
    at param (\node_modules\express\lib\router\index.js:354:14)
    at param (\node_modules\express\lib\router\index.js:365:14)
    at Function.process_params (\node_modules\express\lib\router\index.js:410:3)
    at next (\node_modules\express\lib\router\index.js:275:10)
	...
```

The error appears when using baucis v. **1.6.6** but not on **1.6.5** (both paired with mongoose v. 4.4.20 ) so I strongly think is related to: #323

**Comment by wprl** [comment]
Republished 1.6.5 as 1.6.7 as a temporary solution.
