### ISSUE TITLE
Error [ERR_HTTP_TRAILER_INVALID]: Trailers are invalid with this transfer encoding     at ServerResponse._storeHeader (_http_outgoing.js:424:11)     at ServerResponse.writeHead (_http_server.js:256:8)     at ServerResponse._implicitHeader (_http_server.js:184:8)     at write_ (_http_outgoing.js:641:9)     at ServerResponse.end (_http_outgoing.js:762:5)     at write (/home/hernan/Proyectos/posgrados/api-posgrados/node_modules/finalhandler/index.js:297:9)     at send (/home/hernan/Proyectos/posgrados/api-posgrados/node_modules/finalhandler/index.js:301:5)     at Immediate.<anonymous> (/home/hernan/Proyectos/posgrados/api-posgrados/node_modules/finalhandler/index.js:133:5)     at Immediate.<anonymous> (/home/hernan/Proyectos/posgrados/api-posgrados/node_modules/express/lib/router/index.js:635:15)     at runCallback (timers.js:757:11)     at tryOnImmediate (timers.js:717:5)

### ISSUE THREAD

**Issue by HernanGH** [wprl/baucis#330]
`Error [ERR_HTTP_TRAILER_INVALID]: Trailers are invalid with this transfer encoding
    at ServerResponse._storeHeader (_http_outgoing.js:424:11)
    at ServerResponse.writeHead (_http_server.js:256:8)
    at ServerResponse._implicitHeader (_http_server.js:184:8)
    at write_ (_http_outgoing.js:641:9)
    at ServerResponse.end (_http_outgoing.js:762:5)
    at write ([dir]/api-posgrados/node_modules/finalhandler/index.js:297:9)
    at send ([dir]/api-posgrados/node_modules/finalhandler/index.js:301:5)
    at Immediate.<anonymous> (/[dir]/api-posgrados/node_modules/finalhandler/index.js:133:5)
    at Immediate.<anonymous> (/[dir]/api-posgrados/node_modules/express/lib/router/index.js:635:15)
    at runCallback (timers.js:757:11)
    at tryOnImmediate (timers.js:717:5)
`

**This error occurs with the latest buacis version when I run it with node v9.10 :(**

**Comment by pjmolina** [comment]
Do it works on a previous version of node?
Could you share a minimal sample code to reproduce it?

**Comment by HernanGH** [comment]
Yes, it do.
`const baucis     = require('baucis');
const models     = require('./lib/models');
const decorators = require('./lib/decorators');

function buildBaucis() {
    Object.keys(models).forEach((key) => {
        if (Object.keys(decorators).indexOf(key) !== -1) {
            decorators[key](baucis.rest(key));
        } else {
            baucis.rest(key);
        }
    });
    return baucis();
}`

**Comment by pjmolina** [comment]
+1 Reproduced also with node `v9.8.0`

**Comment by swordfish444** [comment]
@wprl Has you made any progress on this? With Node v8 approaching EOL, this seems crucial.

**Comment by maxiejbe** [comment]
@swordfish444 I've experienced this issue while running locally. Will take a look soon!

**Comment by maxiejbe** [comment]
@swordfish444  MR ready! https://github.com/wprl/baucis/pull/335.
