### ISSUE TITLE
test error: Can't set headers after they are sent.

### ISSUE THREAD

**Issue by ivanhuay** [wprl/baucis#331]
# Error in test 
express@4.16.3
mongoose@4.13.14
node lts v8.11.3
### stack:
```
Headers
    ✓ sets Last-Modified for single documents
Error: Can't set headers after they are sent.
    at validateHeader (_http_outgoing.js:491:11)
    at ServerResponse.setHeader (_http_outgoing.js:498:3)
    at vary (/home/percho/Dev/grava/baucis/node_modules/vary/index.js:147:9)
    at ServerResponse.res.vary (/home/percho/Dev/grava/baucis/node_modules/express/lib/response.js:967:3)
    at ServerResponse.res.format (/home/percho/Dev/grava/baucis/node_modules/express/lib/response.js:667:8)
    at Function.baucis.formatters (/home/percho/Dev/grava/baucis/index.js:55:12)
    at /home/percho/Dev/grava/baucis/Controller/errors.js:105:12
    at Layer.handle_error (/home/percho/Dev/grava/baucis/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/home/percho/Dev/grava/baucis/node_modules/express/lib/router/index.js:315:13)
    at /home/percho/Dev/grava/baucis/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/percho/Dev/grava/baucis/node_modules/express/lib/router/index.js:335:12)
    at next (/home/percho/Dev/grava/baucis/node_modules/express/lib/router/index.js:275:10)
    at /home/percho/Dev/grava/baucis/Controller/errors.js:92:5
    at Layer.handle_error (/home/percho/Dev/grava/baucis/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/home/percho/Dev/grava/baucis/node_modules/express/lib/router/index.js:315:13)
    at /home/percho/Dev/grava/baucis/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/percho/Dev/grava/baucis/node_modules/express/lib/router/index.js:335:12)
    at next (/home/percho/Dev/grava/baucis/node_modules/express/lib/router/index.js:275:10)
    at /home/percho/Dev/grava/baucis/Controller/errors.js:83:65
    at Layer.handle_error (/home/percho/Dev/grava/baucis/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/home/percho/Dev/grava/baucis/node_modules/express/lib/router/index.js:315:13)
    at /home/percho/Dev/grava/baucis/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/percho/Dev/grava/baucis/node_modules/express/lib/router/index.js:335:12)
    at next (/home/percho/Dev/grava/baucis/node_modules/express/lib/router/index.js:275:10)
    at /home/percho/Dev/grava/baucis/Controller/errors.js:75:68
    at Layer.handle_error (/home/percho/Dev/grava/baucis/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/home/percho/Dev/grava/baucis/node_modules/express/lib/router/index.js:315:13)
    at /home/percho/Dev/grava/baucis/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/percho/Dev/grava/baucis/node_modules/express/lib/router/index.js:335:12)
    at next (/home/percho/Dev/grava/baucis/node_modules/express/lib/router/index.js:275:10)
    at /home/percho/Dev/grava/baucis/Controller/errors.js:49:7
    at Layer.handle_error (/home/percho/Dev/grava/baucis/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/home/percho/Dev/grava/baucis/node_modules/express/lib/router/index.js:315:13)
    at /home/percho/Dev/grava/baucis/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/percho/Dev/grava/baucis/node_modules/express/lib/router/index.js:335:12)
    at next (/home/percho/Dev/grava/baucis/node_modules/express/lib/router/index.js:275:10)
    at /home/percho/Dev/grava/baucis/Controller/errors.js:36:29
    at Layer.handle_error (/home/percho/Dev/grava/baucis/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/home/percho/Dev/grava/baucis/node_modules/express/lib/router/index.js:315:13)
    at /home/percho/Dev/grava/baucis/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/percho/Dev/grava/baucis/node_modules/express/lib/router/index.js:335:12)
    at Immediate.next (/home/percho/Dev/grava/baucis/node_modules/express/lib/router/index.js:275:10)
    at Immediate._onImmediate (/home/percho/Dev/grava/baucis/node_modules/express/lib/router/index.js:635:15)
    at runCallback (timers.js:812:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
    1) sets Last-Modified for the collection


  18 passing (3s)
  1 failing

  1) Headers sets Last-Modified for the collection:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
  
```

**Comment by ivanhuay** [comment]
investigating a bit I found that in the test `sets Last-Modified for the collection`

response.headers['content-type'] is equal to 'application/json; charset=utf-8'
